// ============================================================
// EngineResponse.cs
// ------------------------------------------------------------
// Data Transfer Object (DTO) returned by ChatbotEngine.ProcessInput().
//
// Rather than returning a plain string, the engine returns this object
// so the UI can access additional metadata without the engine needing
// to know anything about WPF or UI controls.
//
// Properties
// ----------
// Message             — The text to display inside the chat bubble.
// IsSentimentResponse — True when the reply was triggered by an
//                       emotional keyword (e.g. "worried", "scared").
//                       The UI can use this flag for future styling
//                       (e.g. a different bubble colour for empathetic replies).
// TopicLabel          — Human-readable label for the matched topic.
//                       Examples: "phishing", "password", "Sentiment: worried".
//                       Useful for a status bar or debug log.
// ============================================================

namespace CybersecurityChatbotWPF
{

    // Carries the chatbot's reply and contextual metadata back to the UI layer.
    // Keeps the engine decoupled from WPF — the engine only populates this DTO;
    // MainWindow decides how to render it.
    public class EngineResponse
    {
        // ── Properties ────────────────────────────────────────────────

        //The full response text to display in the chat bubble.
        public string Message { get; set; }

        // True when the response was generated by sentiment detection
        // (e.g. the user said "I'm worried" or "I'm frustrated").
        // False for keyword-matched or fallback responses.
        public bool IsSentimentResponse { get; set; }

        // A short label identifying what the engine matched.
        // Examples: "password", "phishing", "Sentiment: curious".
        // Empty string if no specific topic was identified (fallback).
        public string TopicLabel { get; set; }

        // ── Constructor ───────────────────────────────────────────────

          
        // Creates a new EngineResponse.
        
        // <param name="message">The reply text to display.</param>
        // <param name="isSentiment">
        //   Pass true when this reply was triggered by sentiment detection.
        //   Defaults to false.
        // </param>
        // <param name="topicLabel">
        //   Short label for the matched topic. Defaults to an empty string.
        // </param>
        public EngineResponse(string message, bool isSentiment = false, string topicLabel = "")
        {
            Message             = message;
            IsSentimentResponse = isSentiment;
            TopicLabel          = topicLabel;
        }
    }
}
