// ============================================================
// MainWindow.xaml.cs
// ------------------------------------------------------------
// Code-behind for the WPF main window.
//
// The window contains three overlapping Grid controls, each
// representing one screen in the application flow:
//
//   home_grid      Splash screen — logo + "Get Started" button.
//   username_grid  Name entry card — TextBox + "Start Chat" button.
//   chat_grid      Full chat UI — sidebar topics, message list, input bar.
//
// Screens are swapped by toggling Visibility (Hidden/Visible).
// Only one grid is Visible at a time; the others are Hidden.
//
// Chat bubbles are built entirely in code (no XAML DataTemplate)
// so each message can be individualised (colour, label, alignment)
// without a custom ViewModel or data binding.
// ============================================================

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;

namespace CybersecurityChatbotWPF
{

    // Interaction logic for MainWindow.xaml.
    // Handles all UI events and delegates business logic to ChatbotEngine.
    // </summary>
    public partial class MainWindow : Window
    {
        // ── Private fields ─────────────────────────────────────────────


        // The session orchestrator. Owns the UserProfile and ResponseEngine.
        // All input/output passes through this object — the UI never calls
        // ResponseEngine directly.
        // </summary>
        private readonly ChatbotEngine _chatbot;

        // Handles asynchronous WAV playback on startup.
        // Kept as a field so it is not garbage-collected before playback finishes.
        // </summary>
        private readonly AudioHelper _audio;

        // ── Part 3 fields ──────────────────────────────────────────────

        //MySQL access for cybersecurity tasks. See DatabaseHelper.cs.
        private readonly DatabaseHelper _database;

        // Records every significant bot action for the Activity Log panel.
        private readonly ActivityLogger _activityLog;

        // Detects user intent from chat text via keyword/phrase matching.
        private readonly NlpHelper _nlp;

        // Orchestrates Task Assistant actions (add/view/complete/delete) against the DB.
        private readonly TaskAssistantHandler _taskAssistant;

        // Owns the question bank, current question, and score for the quiz.
        private readonly QuizEngine _quiz;


        // The option index the user has currently selected for the active quiz
        // question, or -1 if none selected yet. Reset each time a new question loads.
        private int _selectedQuizOptionIndex = -1;


        // Cache of the most recently loaded task list, used so button click
        // handlers (Complete/Delete) can look up a task's Id without re-querying
        // the database on every click.
        private List<TaskItem> _loadedTasks = new List<TaskItem>();

        // ── Constructor ────────────────────────────────────────────────


        // Initialises the window, wires up the chatbot engine, and plays the greeting.
        //  WPF calls this before the window is shown, so InitializeComponent() must
        // be the very first statement — it parses the XAML and creates all controls.
        public MainWindow()
        {
            InitializeComponent();        // Generated by XAML compiler — creates all controls

            _chatbot = new ChatbotEngine();  // Build knowledge base (ResponseEngine constructor)
            _audio   = new AudioHelper();

            // Play the greeting on a background thread so the window opens immediately
            _audio.PlayGreetingAsync();

            // ── Part 3 setup ──────────────────────────────────────────
            _database      = new DatabaseHelper();
            _activityLog   = new ActivityLogger();
            _nlp           = new NlpHelper();
            _taskAssistant = new TaskAssistantHandler(_database, _activityLog, _nlp);
            _quiz          = new QuizEngine();

            // Initialise the MySQL database/table on startup. This runs async
            // so it never blocks the window from opening; the Task panel checks
            // _database.IsAvailable before allowing actions and shows a clear
            // message if the connection failed.
            _ = InitialiseDatabaseOnStartupAsync();
        }


        // Connects to MySQL and ensures the `tasks` table exists.
        // Runs once at startup. If the connection fails (e.g. MySQL service
        // not running), the Task panel will show an explanatory message
        // instead of crashing — the rest of the app keeps working normally.
        private async Task InitialiseDatabaseOnStartupAsync()
        {
            bool success = await _database.InitialiseDatabaseAsync();

            // Update the Task panel's status text on the UI thread.
            // (We're already on the UI thread here since this was awaited
            // from the constructor without ConfigureAwait(false), but being
            // explicit about Dispatcher usage is good practice for async UI code.)
            Dispatcher.Invoke(() =>
            {
                tasks_db_status_text.Text = success
                    ? ""
                    : "⚠️ Could not connect to MySQL. Make sure your local MySQL server is running.";
            });
        }

        // ── Screen 1 → Screen 2: Home → Name entry ────────────────────


        /// Click handler for the "Get Started" button on the home screen.
        // Hides the home grid and shows the username entry card.
        // Moves keyboard focus to the name TextBox so the user can type immediately.
        private void proceed(object sender, RoutedEventArgs e)
        {
            home_grid.Visibility     = Visibility.Hidden;
            username_grid.Visibility = Visibility.Visible;
            usernames_input.Focus();   // Autofocus the name field for convenience
        }

        // ── Screen 2: Name entry ───────────────────────────────────────


        // KeyDown handler on the username TextBox.
        // Allows the user to press Enter instead of clicking "Start Chat".
        private void username_input_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Enter)
                submit_name(sender, e);   // Reuse the same handler as the button
        }


        // Click handler for the "Start Chat" button (also called by Enter key).
        // Validates the name, initialises the engine, and transitions to the chat screen.
        private void submit_name(object sender, RoutedEventArgs e)
        {
            // Validation: do not allow empty or whitespace-only names.
            // ShowMessage is safe to call here even though the chat grid is hidden —
            // the bubble is added to the ListView so it will be visible when the grid shows.
            if (string.IsNullOrWhiteSpace(usernames_input.Text))
            {
                ShowMessage("Bot", "Please enter a name to continue.");
                return;
            }

            // Initialise the engine: creates a UserProfile with the trimmed name
            _chatbot.Initialise(usernames_input.Text.Trim());

            // Transition to the chat screen
            username_grid.Visibility = Visibility.Hidden;
            chat_grid.Visibility     = Visibility.Visible;

            // Display the personalised welcome message as the first chat bubble
            ShowMessage("Bot", _chatbot.GetWelcomeMessage());

            // Move focus to the chat input so the user can type straight away
            question.Focus();
        }

        // ── Screen 3: Chat ─────────────────────────────────────────────


        // KeyDown handler on the chat input TextBox.
        // Pressing Enter sends the message, matching the behaviour of most chat apps.
        private void question_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Enter)
                send(sender, e);
        }

        // Click handler for the "Send" button (also called by Enter key).
        // Reads the input, shows the user's bubble, gets the bot's reply,
        // shows the bot's bubble, increments the message counter, and
        // refreshes the memory panel.
        private async void send(object sender, RoutedEventArgs e)
        {
            string userInput = question.Text.Trim();

            // Do nothing if the input is empty or just whitespace
            if (string.IsNullOrWhiteSpace(userInput)) return;

            // 1. Show the user's message in a green bubble on the right side
            ShowMessage(_chatbot.UserName, userInput);
            question.Clear();

            // 2. PART 3: Run the NLP simulation first. If it recognises an
            //    intent (add task, set reminder, start quiz, show log, etc.),
            //    handle it directly and skip the Part 2 keyword/sentiment engine.
            //    This lets natural phrasing like "remind me to update my
            //    password tomorrow" trigger real actions from the chat box,
            //    while anything NOT recognised (e.g. "tell me about phishing")
            //    falls through unchanged to the existing Part 1/2 behaviour.
            NlpResult nlpResult = _nlp.Detect(userInput);

            if (nlpResult.Intent != NlpIntent.None)
            {
                string botReply = await HandleNlpIntentAsync(nlpResult, userInput);
                ShowMessage("Bot", botReply);
                _chatbot.IncrementMessages();
                RefreshMemoryPanel();
                return;
            }

            // 3. No NLP intent matched — fall back to the original Part 2 engine.
            EngineResponse response = _chatbot.ProcessInput(userInput);
            ShowMessage("Bot", response.Message);
            _chatbot.IncrementMessages();
            RefreshMemoryPanel();
        }

        // PART 3 — Executes the action implied by a recognised NLP intent
        // and returns the bot's chat-style reply text. Every branch logs
        // its action to ActivityLogger, matching the brief's requirement
        // that NLP-driven actions appear in the activity log.
        private async Task<string> HandleNlpIntentAsync(NlpResult result, string originalInput)
        {
            switch (result.Intent)
            {
                case NlpIntent.AddTask:
                {
                    string title = string.IsNullOrWhiteSpace(result.Detail) ? "New cybersecurity task" : result.Detail;
                    var (success, message, _) = await _taskAssistant.AddTaskAsync(title, title, null);
                    _activityLog.Log($"NLP recognised 'add task' intent from chat input", "NLP");
                    return success ? message + "\n\n(You can also manage tasks from the Tasks panel.)" : message;
                }

                case NlpIntent.SetReminder:
                {
                    // The brief's example treats "remind me to X" as adding a task
                    // WITH a reminder attached, e.g.:
                    //   "Remind me to update my password tomorrow."
                    //   -> "Reminder set for 'Update my password' on tomorrow's date."
                    string title = string.IsNullOrWhiteSpace(result.Detail) ? "Reminder" : result.Detail;
                    TimeSpan? offset = _nlp.ExtractTimeframe(originalInput);
                    DateTime reminderDate = DateTime.Now.Add(offset ?? TimeSpan.FromDays(3));

                    var (success, message, _) = await _taskAssistant.AddTaskAsync(title, title, reminderDate);
                    _activityLog.Log("NLP recognised 'set reminder' intent from chat input", "NLP");
                    return success
                        ? $"Reminder set for '{title}' on {reminderDate:dd MMM yyyy}."
                        : message;
                }

                case NlpIntent.ViewTasks:
                {
                    List<TaskItem> tasks = await _taskAssistant.GetAllTasksAsync();
                    return _taskAssistant.FormatTaskListForChat(tasks);
                }

                case NlpIntent.CompleteTask:
                {
                    TaskItem match = await _taskAssistant.FindTaskByTitleFragmentAsync(result.Detail);
                    if (match == null)
                        return "I couldn't find a matching task. Try checking the Tasks panel for exact titles.";
                    var (success, message) = await _taskAssistant.CompleteTaskAsync(match.Id, match.Title);
                    return message;
                }

                case NlpIntent.DeleteTask:
                {
                    TaskItem match = await _taskAssistant.FindTaskByTitleFragmentAsync(result.Detail);
                    if (match == null)
                        return "I couldn't find a matching task to delete. Try checking the Tasks panel for exact titles.";
                    var (success, message) = await _taskAssistant.DeleteTaskAsync(match.Id, match.Title);
                    return message;
                }

                case NlpIntent.StartQuiz:
                {
                    // Switch the user straight into the Quiz panel and start a fresh attempt,
                    // mirroring how clicking the sidebar "Quiz" button behaves.
                    nav_button_Click(nav_quiz_button, new RoutedEventArgs());
                    start_quiz_button_Click(this, new RoutedEventArgs());
                    return "Let's test your cybersecurity knowledge! I've opened the quiz for you. 🛡️";
                }

                case NlpIntent.ShowActivityLog:
                    return _activityLog.GetFormattedSummary(showAll: false);

                case NlpIntent.ShowMoreActivityLog:
                    return _activityLog.GetFormattedSummary(showAll: true);

                default:
                    return "I'm not sure how to help with that yet.";
            }
        }

        // ── Sidebar topic buttons ──────────────────────────────────────

        // Shared click handler for all 10 topic buttons in the left sidebar.
        // Each button's Tag property holds the topic keyword (e.g. "phishing").
        // Clicking a button behaves exactly like typing that keyword and pressing Send.
        private void topic_button_Click(object sender, RoutedEventArgs e)
        {
            // Cast the generic sender to Button and read its Tag
            if (sender is Button btn && btn.Tag is string topic)
            {
                // Show the topic keyword as if the user typed it
                ShowMessage(_chatbot.UserName, topic);

                // Get the response from the engine (same path as manual typing)
                EngineResponse response = _chatbot.ProcessInput(topic);

                ShowMessage("Bot", response.Message);
                _chatbot.IncrementMessages();
                RefreshMemoryPanel();
            }
        }

        // ── Part 3: Top-level navigation (Chat / Tasks / Quiz / Log) ──


        /// Shared click handler for the four sidebar navigation buttons.
        // Each button's Tag identifies which panel to show: "chat", "tasks",
        // "quiz", or "log". Exactly one of the four panel grids is Visible
        // at a time — the rest are Hidden, mirroring the existing
        // home/username/chat screen-switching pattern.
        // </summary>
        private void nav_button_Click(object sender, RoutedEventArgs e)
        {
            if (!(sender is Button btn && btn.Tag is string target)) return;

            // Hide all four panels, then show only the requested one.
            chat_panel_grid.Visibility  = Visibility.Hidden;
            tasks_panel_grid.Visibility = Visibility.Hidden;
            quiz_panel_grid.Visibility  = Visibility.Hidden;
            log_panel_grid.Visibility   = Visibility.Hidden;

            switch (target)
            {
                case "chat":
                    chat_panel_grid.Visibility = Visibility.Visible;
                    question.Focus();
                    break;

                case "tasks":
                    tasks_panel_grid.Visibility = Visibility.Visible;
                    _ = RefreshTaskListAsync();
                    break;

                case "quiz":
                    quiz_panel_grid.Visibility = Visibility.Visible;
                    break;

                case "log":
                    log_panel_grid.Visibility = Visibility.Visible;
                    RefreshActivityLog(showAll: false);
                    break;
            }
        }

        // ── Part 3: Task Assistant panel ───────────────────────────────

        // Click handler for "Add Task". Reads the title and reminder
        // selection from the form, adds the task via TaskAssistantHandler,
        // and refreshes the task list.
        private async void add_task_button_Click(object sender, RoutedEventArgs e)
        {
            string title = new_task_title_input.Text.Trim();
            if (string.IsNullOrWhiteSpace(title))
            {
                MessageBox.Show("Please enter a task title first.", "Task Assistant",
                                 MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            DateTime? reminderDate = GetReminderDateFromCombo();

            var (success, message, _) = await _taskAssistant.AddTaskAsync(title, title, reminderDate);

            if (!success)
                MessageBox.Show(message, "Task Assistant", MessageBoxButton.OK, MessageBoxImage.Warning);

            new_task_title_input.Clear();
            new_task_reminder_combo.SelectedIndex = 0;

            await RefreshTaskListAsync();
        }

        // Translates the reminder ComboBox selection into a concrete
        // DateTime, or null if "No reminder" is selected.
        private DateTime? GetReminderDateFromCombo()
        {
            switch (new_task_reminder_combo.SelectedIndex)
            {
                case 1: return DateTime.Now.AddDays(1);
                case 2: return DateTime.Now.AddDays(3);
                case 3: return DateTime.Now.AddDays(7);
                default: return null; // "No reminder"
            }
        }

        // Reloads the task list from the database and rebuilds the
        // ListView content. Each task row shows its title, description,
        // reminder date (if any), and Complete/Delete buttons.
        private async Task RefreshTaskListAsync()
        {
            _loadedTasks = await _taskAssistant.GetAllTasksAsync();

            tasks_list_view.Items.Clear();

            if (_loadedTasks.Count == 0)
            {
                tasks_list_view.Items.Add(BuildEmptyStateRow(
                    _database.IsAvailable
                        ? "No tasks yet — add one above to get started."
                        : "Task list unavailable — MySQL is not connected."));
                return;
            }

            foreach (TaskItem task in _loadedTasks)
                tasks_list_view.Items.Add(BuildTaskRow(task));
        }


        /// Builds a single visual row for one task: title, description,
        // reminder badge (if set), and Complete/Delete buttons.
        // Built in code (not XAML DataTemplate) for the same reason
        // ShowMessage builds chat bubbles in code — each row needs
        // individualised content and per-row button event wiring.
        // </summary>
        private Border BuildTaskRow(TaskItem task)
        {
            Border row = new Border
            {
                Margin = new Thickness(6, 6, 6, 6),
                Padding = new Thickness(14, 12, 14, 12),
                CornerRadius = new CornerRadius(10),
                Background = task.IsCompleted
                    ? new SolidColorBrush(Color.FromRgb(240, 253, 244))   // pale green = done
                    : new SolidColorBrush(Color.FromRgb(249, 250, 251))  // pale grey = pending
            };

            Grid grid = new Grid();
            grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
            grid.ColumnDefinitions.Add(new ColumnDefinition { Width = GridLength.Auto });
            grid.ColumnDefinitions.Add(new ColumnDefinition { Width = GridLength.Auto });

            // Left: title + description + reminder
            StackPanel textPanel = new StackPanel { Margin = new Thickness(0, 0, 12, 0) };

            TextBlock titleBlock = new TextBlock
            {
                Text = task.Title,
                FontWeight = FontWeights.SemiBold,
                FontSize = 14,
                TextWrapping = TextWrapping.Wrap,
                Foreground = task.IsCompleted ? Brushes.Gray : Brushes.Black,
                TextDecorations = task.IsCompleted ? TextDecorations.Strikethrough : null
            };
            textPanel.Children.Add(titleBlock);

            if (!string.IsNullOrWhiteSpace(task.Description) && task.Description != task.Title)
            {
                textPanel.Children.Add(new TextBlock
                {
                    Text = task.Description,
                    FontSize = 12,
                    Foreground = Brushes.Gray,
                    TextWrapping = TextWrapping.Wrap,
                    Margin = new Thickness(0, 2, 0, 0)
                });
            }

            if (task.ReminderDate.HasValue)
            {
                textPanel.Children.Add(new TextBlock
                {
                    Text = $"⏰ Reminder: {task.ReminderDate.Value:dd MMM yyyy}",
                    FontSize = 11,
                    Foreground = new SolidColorBrush(Color.FromRgb(37, 99, 235)),
                    Margin = new Thickness(0, 4, 0, 0)
                });
            }

            Grid.SetColumn(textPanel, 0);
            grid.Children.Add(textPanel);

            // Complete button (hidden if already completed)
            if (!task.IsCompleted)
            {
                Button completeBtn = new Button
                {
                    Content = "✓ Complete",
                    Width = 100,
                    Style = (Style)FindResource("PrimaryActionButtonStyle"),
                    Margin = new Thickness(0, 0, 8, 0),
                    Tag = task.Id
                };
                completeBtn.Click += async (s, e) =>
                {
                    var (success, message) = await _taskAssistant.CompleteTaskAsync(task.Id, task.Title);
                    if (!success) MessageBox.Show(message, "Task Assistant");
                    await RefreshTaskListAsync();
                };
                Grid.SetColumn(completeBtn, 1);
                grid.Children.Add(completeBtn);
            }

            // Delete button
            Button deleteBtn = new Button
            {
                Content = "🗑 Delete",
                Width = 90,
                Style = (Style)FindResource("SecondaryActionButtonStyle"),
                Tag = task.Id
            };
            deleteBtn.Click += async (s, e) =>
            {
                var (success, message) = await _taskAssistant.DeleteTaskAsync(task.Id, task.Title);
                if (!success) MessageBox.Show(message, "Task Assistant");
                await RefreshTaskListAsync();
            };
            Grid.SetColumn(deleteBtn, 2);
            grid.Children.Add(deleteBtn);

            row.Child = grid;
            return row;
        }

        /// <summary>Builds a simple grey placeholder row for empty-state lists.</summary>
        private Border BuildEmptyStateRow(string message)
        {
            return new Border
            {
                Padding = new Thickness(16),
                Child = new TextBlock
                {
                    Text = message,
                    Foreground = Brushes.Gray,
                    FontSize = 13,
                    TextWrapping = TextWrapping.Wrap,
                    HorizontalAlignment = HorizontalAlignment.Center
                }
            };
        }

        // ── Part 3: Quiz panel ──────────────────────────────────────────

        // Click handler for "Start Quiz" / "Play Again". Begins a fresh
        // quiz attempt and displays the first question.
        private void start_quiz_button_Click(object sender, RoutedEventArgs e)
        {
            _quiz.StartNewQuiz();
            _activityLog.Log("Quiz started", "Quiz");

            quiz_start_panel.Visibility   = Visibility.Hidden;
            quiz_results_panel.Visibility = Visibility.Hidden;
            quiz_question_panel.Visibility = Visibility.Visible;

            DisplayCurrentQuizQuestion();
        }


        /// Renders the current question's text and answer options as
        // selectable buttons. Called when the quiz starts and after
        // each "Next Question" click.
        private void DisplayCurrentQuizQuestion()
        {
            QuizQuestion q = _quiz.GetCurrentQuestion();
            if (q == null) return;

            _selectedQuizOptionIndex = -1;

            quiz_progress_text.Text = $"Question {_quiz.CurrentIndex + 1} of {_quiz.TotalQuestions}  •  Score: {_quiz.Score}";
            quiz_question_text.Text = q.Text;

            quiz_feedback_text.Visibility = Visibility.Collapsed;
            quiz_next_button.Visibility   = Visibility.Collapsed;

            quiz_options_panel.Children.Clear();

            for (int i = 0; i < q.Options.Count; i++)
            {
                int optionIndex = i; // local copy for closure capture
                Button optionBtn = new Button
                {
                    Content = q.Options[i],
                    Margin = new Thickness(0, 0, 0, 8),
                    Height = 40,
                    HorizontalContentAlignment = HorizontalAlignment.Left,
                    Padding = new Thickness(14, 0, 0, 0),
                    Background = new SolidColorBrush(Color.FromRgb(249, 250, 251)),
                    BorderBrush = new SolidColorBrush(Color.FromRgb(209, 213, 219)),
                    BorderThickness = new Thickness(1),
                    Cursor = System.Windows.Input.Cursors.Hand
                };
                optionBtn.Click += (s, e) => SubmitQuizAnswer(optionIndex, optionBtn);
                quiz_options_panel.Children.Add(optionBtn);
            }
        }

        /// <summary>
        /// Handles the user selecting an answer option: submits it to
        /// QuizEngine, colours the chosen button green/red, shows the
        /// explanation, and reveals the "Next Question" button.
        /// </summary>
        private void SubmitQuizAnswer(int selectedIndex, Button clickedButton)
        {
            // Disable all option buttons after the first answer to prevent re-answering
            foreach (UIElement child in quiz_options_panel.Children)
                if (child is Button b) b.IsEnabled = false;

            var (wasCorrect, explanation) = _quiz.SubmitAnswer(selectedIndex);

            clickedButton.Background = wasCorrect
                ? new SolidColorBrush(Color.FromRgb(220, 252, 231))   // green = correct
                : new SolidColorBrush(Color.FromRgb(254, 226, 226));  // red = incorrect

            quiz_feedback_text.Text = (wasCorrect ? "✅ Correct! " : "❌ Not quite. ") + explanation;
            quiz_feedback_text.Foreground = wasCorrect
                ? new SolidColorBrush(Color.FromRgb(6, 95, 70))
                : new SolidColorBrush(Color.FromRgb(185, 28, 28));
            quiz_feedback_text.Visibility = Visibility.Visible;

            quiz_next_button.Content    = _quiz.IsFinished ? "See Results" : "Next Question";
            quiz_next_button.Visibility = Visibility.Visible;
        }


        // Click handler for "Next Question" / "See Results". Advances
        // to the next question, or shows the final score screen if the
        // quiz is complete.
        private void quiz_next_button_Click(object sender, RoutedEventArgs e)
        {
            if (_quiz.IsFinished)
            {
                quiz_question_panel.Visibility = Visibility.Hidden;
                quiz_results_panel.Visibility  = Visibility.Visible;
                quiz_score_text.Text = _quiz.GetScoreSummary();

                _activityLog.Log($"Quiz completed - scored {_quiz.Score}/{_quiz.TotalQuestions}", "Quiz");
            }
            else
            {
                DisplayCurrentQuizQuestion();
            }
        }

        // ── Part 3: Activity Log panel ──────────────────────────────────

        // Rebuilds the Activity Log ListView from ActivityLogger.
        // <param name="showAll">If true, shows every entry; otherwise the recent few.</param>
        private void RefreshActivityLog(bool showAll)
        {
            log_list_view.Items.Clear();

            List<ActivityLogEntry> entries = showAll ? _activityLog.GetAll() : _activityLog.GetRecent();

            if (entries.Count == 0)
            {
                log_list_view.Items.Add(BuildEmptyStateRow("No actions logged yet this session."));
                log_show_more_button.Visibility = Visibility.Collapsed;
                return;
            }

            foreach (ActivityLogEntry entry in entries)
                log_list_view.Items.Add(BuildLogRow(entry));

            // Only offer "Show more" if there are additional older entries to reveal
            log_show_more_button.Visibility =
                (!showAll && _activityLog.Count > entries.Count) ? Visibility.Visible : Visibility.Collapsed;
        }

        // Builds a single visual row for one activity log entry.
        private Border BuildLogRow(ActivityLogEntry entry)
        {
            return new Border
            {
                Margin = new Thickness(6, 4, 6, 4),
                Padding = new Thickness(12, 10, 12, 10),
                CornerRadius = new CornerRadius(8),
                Background = new SolidColorBrush(Color.FromRgb(249, 250, 251)),
                Child = new TextBlock
                {
                    Text = entry.ToString(),
                    FontSize = 13,
                    TextWrapping = TextWrapping.Wrap,
                    Foreground = Brushes.Black
                }
            };
        }

        // Click handler for "Show Full History".
        private void log_show_more_button_Click(object sender, RoutedEventArgs e)
        {
            RefreshActivityLog(showAll: true);
        }

        // Creates a styled chat bubble and adds it to the message list (chats ListView).
        // Bot bubbles are blue-tinted and left-aligned.
        // User bubbles are green-tinted and right-aligned (achieved via left margin).
        // </summary>
        // <param name="sender">
        //   "Bot" for the bot's replies; the user's name for their messages.
        // </param>
        // <param name="message">The text content of the bubble.</param>
        private void ShowMessage(string sender, string message)
        {
            // Determine the bubble side by checking whether the sender is the bot
            bool isBot = sender == "Bot";

            // ── Bubble container ──────────────────────────────────────
            // Left margin pushes user bubbles to the right (60px indent from left).
            // Right margin pushes bot bubbles away from the right edge.
            Border bubble = new Border
            {
                Margin        = new Thickness(isBot ? 0 : 60, 4, isBot ? 60 : 0, 4),
                Padding       = new Thickness(14, 10, 14, 10),
                CornerRadius  = new CornerRadius(12),
                Background    = isBot
                                    ? new SolidColorBrush(Color.FromRgb(224, 237, 255))  // light blue
                                    : new SolidColorBrush(Color.FromRgb(220, 252, 231)), // light green
                BorderThickness = new Thickness(0)
            };

            // ── Text block with two Runs ──────────────────────────────
            // Run 1: sender label in bold (with emoji prefix)
            // Run 2: message body in normal weight
            // Using Inlines instead of two separate TextBlocks keeps the
            // label and message in the same wrapping flow.
            TextBlock tb = new TextBlock
            {
                TextWrapping = TextWrapping.Wrap,
                FontSize     = 14
            };

            // Bold sender label — dark blue for bot, dark green for user
            tb.Inlines.Add(new Run
            {
                Text       = (isBot ? "🤖 Bot" : $"👤 {sender}") + "\n",
                FontWeight = FontWeights.Bold,
                Foreground = isBot
                             ? new SolidColorBrush(Color.FromRgb(30, 58, 95))   // dark navy
                             : new SolidColorBrush(Color.FromRgb(6, 95, 70))    // dark green
            });

            // Normal-weight message body in black for readability
            tb.Inlines.Add(new Run
            {
                Text       = message,
                Foreground = Brushes.Black
            });

            bubble.Child = tb;

            // Add bubble to the ListView and scroll it into view immediately
            chats.Items.Add(bubble);
            chats.ScrollIntoView(bubble);
        }


        /// Reads the current memory summary from the engine and updates
        // the sidebar TextBlock (memory_panel).
        // Called after every message send so the panel stays current.
        private void RefreshMemoryPanel()
        {
            string summary = _chatbot.GetMemorySummary();

            // Show a hint string if nothing has been remembered yet,
            // so the panel is never blank and confusing to the user.
            memory_panel.Text = string.IsNullOrEmpty(summary)
                                ? "Nothing remembered yet."
                                : summary;
        }
    }
}
